add decorative elements
htmlacademy-htmlcss/1853163-sedona-33 pull request #7
Opened 2022-02-27 10:42 UTC by olgapecheniuk

2022-02-28 08:55 UTC, nikopol-fw requested changes

2022-02-28 08:55 UTC, nikopol-fw commented on index.html
>      <div class="navigation-menu">
От этого div'а разве есть какая-то польза?

2022-02-28 08:55 UTC, nikopol-fw commented on styles/styles.css
> +  border-bottom: 2px solid #756257;
border следует создать для всех ссылок, но сделать его прозрачным. Не очень хорошо, когда при наведении на элемент или иное его размеры меняются.

2022-02-28 08:55 UTC, nikopol-fw commented on styles/styles.css
>  .navigation-logo {
Зачем логотипу строго фиксировать размер?

2022-02-28 08:55 UTC, nikopol-fw commented on styles/styles.css
>    max-width: 300px;
Следует ли ограничивать размер этому списку?
Лучше задать запрет на сжатие и расширение flex: 0 0 auto
В остальном по идее, пусть это меню забирает столько места, сколько ему нужно. По контенту особо не предполагается генерация значительного количества новых пунктов

2022-03-02 11:00 UTC, olgapecheniuk commented on index.html
>      <div class="navigation-menu">
Я бы его оставила, если это не критично. Мне так удобней

2022-03-02 13:11 UTC, nikopol-fw approved these changes

2022-03-02 13:12 UTC, merged